### ISSUE TITLE
Support NextJS

### ISSUE THREAD

**Issue by dbredvick** [LogRocket/logrocket-react#16]
Per the `logrocket-react` [docs](https://docs.logrocket.com/docs/react-plugin), the React module doesn't support [NextJS](http://nextjs.org/).

I use NextJS on both work and personal projects & would love to be able to use `logrocket-react`.

**Comment by krinoid** [comment]
Agreed. next.js is very popular and I've been using it in multiple projects, with multiple clients. I'd love to be able to integrate these apps with LogRocket. Is there a chance we could get some official response? Is it possible in the near future or somehow it won't be possible to use LogRocket with next.js for a long time? Thanks!

**Comment by Otomakan** [comment]
Have you looked at https://docs.logrocket.com/docs/using-logrocket-with-server-side-rendering?

**Comment by krinoid** [comment]
Thanks, @Otomakan! I've previously misunderstood docs and thought that logrocket doesn't support next.js at all but it seems that only logrocket-react is not properly supported (but that's just filtering events per components, which is not that important for me).

**Comment by Otomakan** [comment]
Yes, things are really confusing in nextjs! Nextjs is evolving super fast, you have to keep track of what version you're using, what versions are supported with the tools you want to use. And more often than not when you have an extra dependency it can break everything.

**Comment by kylemh** [comment]
I think the language should be adjusted on the docs page.

I love Next.js and LogRocket as well, and am able to use both no problem.

Just need to follow the docs that @Otomakan listed.
